services:
    auth:
        command: node dist/src/main.js

    site:
        command: node_modules/.bin/next start

    # game-static não precisa de command. o nginx do container já cuida

    game-server:
        command: node dist/server.js

    postgres:
        ports: []

    redis:
        ports: []
